[project]
name = "testrepo"
readme = "README.md"
license = {file = "LICENSE.md"}
requires-python = ">=3.12 <3.13"

[tool.poetry]
name = "testrepo"
version = "0.0.0"  # DO NOT CHANGE -- set during build
description = "Easily monitor your small compute environments."
authors = ["Paul Lockaby <paul@paullockaby.com>"]
packages = [{include = "testrepo", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12 <3.13"
quart = "^0.19.6"
hypercorn = {extras = ["uvloop"], version = "^0.17.3"}

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.1"
pytest-cov = "^5.0.0"
pytest-mypy = "^0.10.3"
pytest-asyncio = "^0.23.8"
pre-commit = "^3.7.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
